@url = http://localhost:5000/solution-to-problem
#@url = https://the80by20.azurewebsites.net/solution-to-problem

@accessToken = secret

###
GET {{url}}

###
POST {{url}}/solutions/FinishSolutionMocked

