@url = http://localhost:5000
#@url = https://the80by20.azurewebsites.net

@userId = 00000000-0000-0000-0000-000000000001

###
GET {{url}}/api

###
GET {{url}}/users/users/{{userId}}



###
# @name sign_in
POST {{url}}/users/users/sign-in
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###
# @name sign_in
POST {{url}}/users/users/sign-in
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}

###
GET {{url}}/users/users/me
Authorization: Bearer {{accessToken}}

// only-admin
###
GET {{url}}/users/users
Authorization: Bearer {{accessToken}}

// only-admin
###
@admin-id = a3469e46-fbc5-44a3-8579-b2a7d810cfcb
GET {{url}}/users/users/{{admin-id}}
Authorization: Bearer {{accessToken}}

###
POST {{url}}/solution-to-problem/problems
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "description": "",
  "category": "00000000-0000-0000-0000-000000000003",
  "userId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "solutionElementTypes": [
    0
  ]
}