@url = http://localhost:5000
#@url = https://the80by20.azurewebsites.net

@userId = 00000000-0000-0000-0000-000000000001

###
GET {{url}}/api

###
GET {{url}}/security/users/{{userId}}

###
POST {{url}}/security/users
Content-Type: application/json

{
    "email": "user1@wp.pl",
    "username": "user1",
    "password": "secret",
    "fullName": "Jan Jo",
    "role": "user"
}


###
# @name sign_in
POST {{url}}/security/users/sign-in
Content-Type: application/json

{
    "email": "user1@wp.pl",
    "password": "secret"
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}

###
GET {{url}}/security/users/me
Authorization: Bearer {{accessToken}}

// only-admin
###
GET {{url}}/security/users
Authorization: Bearer {{accessToken}}

###
POST {{url}}/solution-to-problem/problems
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "description": "",
  "category": "00000000-0000-0000-0000-000000000003",
  "userId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "solutionElementTypes": [
    0
  ]
}