# based on: https://learn.microsoft.com/en-us/dotnet/devops/dotnet-publish-github-action
# https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-6.0&tabs=netcore-cli

# todo set appservice to run on linux
name: CI/CD .net backend to azure

env:
    AZURE_WEBAPP_NAME: the80by20        # set this to the name of your Azure Web App
    AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
    DOTNET_VERSION: '6.0.x'             # set this to the .NET Core version to use
    WORKING_DIRECTORY: the80by20


on:
  push:
    branches: [ "main" ]
    paths:
        - 'the80by20/**'
        - '.github/workflows/dotnet.yml'
        - '!the80by20/the80by20/tools/**'
  pull_request: 
    branches: [ "main" ]
# todo pull request on other branches only build without deploy

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './the80by20/src/Bootstrapper/the80by20.Bootstrapper/appsettings.json'
      env:
        dataBase.connectionString: ${{ secrets.connection_string }}      
    
    - name: Install dependencies
      working-directory: ${{env.WORKING_DIRECTORY}}
      run: dotnet restore
      
    - name: Build
      working-directory: ${{env.WORKING_DIRECTORY}}
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ../dotnet-webapp --runtime win-x64 --self-contained true /p:UseAppHost=true
        
    - name: Test
      working-directory: ${{env.WORKING_DIRECTORY}}
      #run: dotnet test --runtime win-x86 --verbosity normal --filter FullyQualifiedName!~the80by20.Sandbox
      run: dotnet test --runtime win-x64 --filter FullyQualifiedName!~the80by20.Sandbox
      
    - uses: azure/webapps-deploy@v2
      name: Deploy
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/dotnet-webapp'
