

name: Build and deploy ASP.Net Core app to an Azure Web App

env:
    AZURE_WEBAPP_NAME: the80by20    # set this to the name of your Azure Web App
    AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
    DOTNET_VERSION: '6.0.x'                 # set this to the .NET Core version to use
    WORKING_DIRECTORY: the80by20


on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]
# todo pull request on other branches only build without deploy

jobs:
 
 ############# BUILD #############
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: App Settings Variable Substitution               
      uses: microsoft/variable-substitution@v1
      with:
        files: './the80by20/src/the80by20.WebApi/appsettings.json'
      env:
        dataBase.connectionString: ${{ secrets.connection_string }}      
    
    - name: Restore dependencies
      working-directory: ${{env.WORKING_DIRECTORY}}
      run: dotnet restore
    
    - name: Build
      working-directory: ${{env.WORKING_DIRECTORY}}
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      working-directory: ${{env.WORKING_DIRECTORY}}
      run: dotnet test --verbosity normal
    
    - name: dotnet publish
      working-directory: ${{env.WORKING_DIRECTORY}}
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

 ############# ARTIFACT #############
 
 ############# DEPLOY #############
 
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'       
      url: "https://the80by20.azurewebsites.net"
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
     
