

name: .NET


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      WorkingDirectory: the80by20

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: WorkingDirectory
      run: dotnet restore
    - name: Build
      working-directory: WorkingDirectory
      run: dotnet build --configuration Release --no-restore
    #- name: Test
     # run: dotnet test --no-build --verbosity normal
